Add F# templates
AvaloniaUI/AvaloniaVS pull request #175
Opened 2020-10-16 13:11 UTC by FoggyFinder

Closes: #174 

Some parts were copied from C# projects, unsure whether it is really necessary to have.

For example

```xml
  <ItemGroup>
    <BootstrapperPackage Include=".NETFramework,Version=v4.6">
      <Visible>False</Visible>
      <ProductName>Microsoft .NET Framework 4.6 %28x86 and x64%29</ProductName>
      <Install>true</Install>
    </BootstrapperPackage>
    <BootstrapperPackage Include="Microsoft.Net.Framework.3.5.SP1">
      <Visible>False</Visible>
      <ProductName>.NET Framework 3.5 SP1</ProductName>
      <Install>false</Install>
    </BootstrapperPackage>
  </ItemGroup>
```

Also, noticed that icons for `User Control`, `Window` templates aren't displayed. Was it done purposely?

Anyway, ready for review and/or feedback

2020-10-24 22:26 UTC, Kir-Antipov requested changes
LGTM, but there're several points:

1. Replacing `$safeitemrootname$` with `$safeitemname$` will make templates a little bit more accessible.
2. Should `nuget.config` really be included in the template? I don't think that the template should in any way affect which sources users choose for their projects.

2020-10-24 22:26 UTC, Kir-Antipov commented on templates/FsAvaloniaWindowTemplate/Window.xaml.fs
> +type $safeitemrootname$ () as self =
`$safeitemrootname$` is equivalent to the `$safeitemname$`, but it's not available in pre-2017 versions that are still in use. So it will be better to replace this with the more accessible `$safeitemname$`.

2020-10-24 22:26 UTC, Kir-Antipov commented on templates/FsAvaloniaWindowTemplate/Window.xaml
> +    Title="$safeitemrootname$"
Same as for [templates/FsAvaloniaWindowTemplate/Window.xaml.fs](https://github.com/AvaloniaUI/AvaloniaVS/pull/175/files#diff-ae5a8606b1789a581e1e75b2cfe0aa7ff0428bde09fb9929406c9de2b5009a96R7).

2020-10-24 22:26 UTC, Kir-Antipov commented on templates/FsAvaloniaUserControlTemplate/UserControl.xaml.fs
> +type $safeitemrootname$ () as self =
`$safeitemrootname$` -> `$safeitemname$`

2020-10-24 22:26 UTC, Kir-Antipov commented on templates/FsAvaloniaUserControlTemplate/UserControl.xaml
> +    x:Class="Views.$safeitemrootname$"
`$safeitemrootname$` -> `$safeitemname$`

2020-10-24 22:26 UTC, Kir-Antipov commented on templates/FsAvaloniaMvvmApplicationTemplate/nuget.config
> +</configuration>
Well, does it really need to be included in the template? Not everyone needs the "unstable" packages

2020-10-25 08:08 UTC, FoggyFinder commented
@Kir-Antipov PR is updated

2020-10-25 08:51 UTC, Kir-Antipov approved these changes
Everything's great, I think

2020-11-01 12:16 UTC, rstm-sf reviewed
Hello! I would like to share a few thoughts on the msbuild part

2020-11-01 12:16 UTC, rstm-sf commented on templates/FsAvaloniaApplicationTemplate/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright © FoggyFinder 2020")]
It seems to me that this information is superfluous :)

In addition, the new sdk does not need this file, since all [csproj can be specified](https://docs.microsoft.com/en-us/dotnet/core/tools/csproj#properties-per-attribute). It is even [possible to specify](https://www.meziantou.net/declaring-internalsvisibleto-in-the-csproj.htm) `InternalsVisibleToAttribute`. But for some reason the old sdk is also added to this pr

2020-11-01 12:16 UTC, rstm-sf commented on templates/FsAvaloniaApplicationTemplate/nuget.config
> +    <add key="AvaloniaCI" value="https://www.myget.org/F/avalonia-ci/api/v2" />
This file is actually superfluous for the new sdk. It can be replaced by `RestoreSources` from `PropertyGroup` to csproj. In addition, now, it seems to me that by default, users were using stable packages from nuget.org. Therefore, it seems that adding this file to templates is unnecessary

2020-11-01 12:43 UTC, FoggyFinder commented on templates/FsAvaloniaApplicationTemplate/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright © FoggyFinder 2020")]
It was Is is auto-generated part. Will it be OK if I just set empty string there?

2020-11-01 12:45 UTC, FoggyFinder commented on templates/FsAvaloniaApplicationTemplate/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright © FoggyFinder 2020")]
> But for some reason the old sdk is also added to this pr

That's because csproj template for templates uses old sdk. I can try to convert to the new one

2020-11-01 13:40 UTC, FoggyFinder commented on templates/FsAvaloniaApplicationTemplate/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright © FoggyFinder 2020")]
I wasn't able to convert to new SDK. Reference to `Microsoft.VisualStudio.CoreUtilit` isn't resolved.

2020-11-01 13:49 UTC, rstm-sf commented on templates/FsAvaloniaApplicationTemplate/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright © FoggyFinder 2020")]
Thank you!

In fact, the studio wizard can, according to what sdk will be, determine whether this file is needed or not. And so, usually in projects with a full framework, these lines still somehow change and make one single file of some kind, so these lines do not need to be added :)

2020-11-05 18:18 UTC, rstm-sf commented on templates/FsAvaloniaApplicationTemplate/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright © FoggyFinder 2020")]
Oops, sorry to bother you, it's my fault. These properties were written for the template. Those. this is not for creating a project and they will not be in the created project

2020-11-05 20:34 UTC, FoggyFinder commented on templates/FsAvaloniaApplicationTemplate/Properties/AssemblyInfo.cs
> +[assembly: AssemblyCopyright("Copyright © FoggyFinder 2020")]
> These properties were written for the template. Those. this is not for creating a project and they will not be in the created project

@rstm-sf I thought you would know it :-) 
Thank you anyway - it's better to keep clean all projects

2020-11-17 13:25 UTC, grokys approved these changes
I'm no expert on F# but these templates seem to work for me! I've taken the liberty of updating the package version to the latest, we'll get this in the new version! :)

2020-11-17 13:51 UTC, merged