add zoom support
AvaloniaUI/AvaloniaVS pull request #180
Opened 2020-11-05 15:29 UTC by donandren

2020-11-05 18:26 UTC, rstm-sf commented on AvaloniaVS/Views/AvaloniaDesigner.xaml.cs
> +            else if (double.TryParse(Zoom.Replace("%", ""), out double zoomPercent) && zoomPercent > 0)
Hello! Maybe using invariant mode for `TryParse` and for `ToString` by double ?

2020-11-05 21:18 UTC, rstm-sf commented on AvaloniaVS/Views/AvaloniaDesigner.xaml.cs
> +            else if (double.TryParse(Zoom.Replace("%", ""), out double zoomPercent) && zoomPercent > 0)
And it seems cleaner to use `TrimEnd` instead of `Replace`

2020-11-06 12:34 UTC, rstm-sf commented on AvaloniaVS/Views/AvaloniaDesigner.xaml.cs
> +            else if (double.TryParse(Zoom.Replace("%", ""), out double zoomPercent) && zoomPercent > 0)
It seems that I understood what the idea of ​​cultural dependence is: it is convenient for the user to see familiar numbers

2020-11-06 15:57 UTC, donandren commented on AvaloniaVS/Views/AvaloniaDesigner.xaml.cs
> +            else if (double.TryParse(Zoom.Replace("%", ""), out double zoomPercent) && zoomPercent > 0)
thanks good to be little bit more on the safe side

2020-11-06 16:47 UTC, rstm-sf commented on AvaloniaVS/Views/AvaloniaDesigner.xaml.cs
> +            else if (double.TryParse(Zoom.Replace("%", ""), out double zoomPercent) && zoomPercent > 0)
In fact, it could have been left as it is, since it happens in one culture, it seems like ... I can't find a case for changing culture. But only these lines would break everything -- it would be possible to use the same `double.ToString`

https://github.com/AvaloniaUI/AvaloniaVS/blob/d326cfb8d4988bc41c32cc317ede84da7bfb95af/AvaloniaVS/Views/AvaloniaDesigner.xaml.cs#L77-L80

2020-11-07 14:19 UTC, grokys requested changes
Looks and works great in general! Just a few small nits in the code and a layout change suggestion.

2020-11-07 14:19 UTC, grokys commented on AvaloniaVS/Views/AvaloniaDesigner.xaml
> +                      Padding="2" local:VsTheme.UseVsTheme="True"/>
When I first ran this, I couldn't find the Zoom `ComboBox` as it's left-aligned while the rest of the controls are on the right. I think the following looks better:

```suggestion
            <ComboBox DockPanel.Dock="Right"
                      Text="{Binding Zoom, ElementName=root, Mode=TwoWay}" IsEditable="True" 
                      ItemsSource="{x:Static local:AvaloniaDesigner.Zooms}"
                      Padding="2" Margin="0 0 10 0" local:VsTheme.UseVsTheme="True"/>
```

![image](https://user-images.githubusercontent.com/1775141/98443581-70292180-210c-11eb-8d49-3500b23258bf.png)

2020-11-17 13:12 UTC, grokys approved these changes
Thanks @donandren - this is great!

2020-11-17 13:12 UTC, merged