feat: Allow discovery internal class
AvaloniaUI/AvaloniaVS pull request #216
Opened 2021-10-21 17:14 UTC by workgroupengineering

fixes #215

2021-11-02 16:03 UTC, workgroupengineering commented
Witing https://github.com/kekekeks/Avalonia.Ide/pull/38 approved

2022-12-27 04:39 UTC, maxkatz6 requested changes
I am not an expert with this area of code but attempted to review it.
Found some problems.

2022-12-27 04:39 UTC, maxkatz6 commented on CompletionEngine/Avalonia.Ide.CompletionEngine/AssemblyMetadata/MetadataConverter.cs
> +            if (types.TryGetValue(key => key.StartsWith("Avalonia.Media.Imaging.IBitmap"), out MetadataType ibitmapType))
I checked why did you need to replace dictionary lookup with loop iterations in many places. And that's because key now is a type's fully qualified name.
But typical simple Avalonia.Samples app has about 2500 types, and there is multiple `TryGetValue(StartsWith)` calls.
Can it be optimized with second dictionary? I think you could do it in PostProcessTypes's scope by iterating over all of these types and creating another local dictionary once.

2022-12-27 04:39 UTC, maxkatz6 commented on tests/CompletionEngineTests/Metadata/MetadataConverterTests.cs
> +        public void Discover_InternalsVisibleTo()
Internal members from other assemblies are still visible, when should not be (https://github.com/AvaloniaUI/AvaloniaVS/issues/130):
![image](https://user-images.githubusercontent.com/3163374/209611420-dabd10f5-4eb9-4f56-a557-7161ed424daf.png)

Other issue with internal types in the same assembly seems to be fixed.

2023-01-03 21:10 UTC, maxkatz6 approved these changes

2023-01-03 21:19 UTC, merged